export const Character = {
  Asta: 'Asta',
  Bailu: 'Bailu',
  BlackSwan: 'BlackSwan',
  Blade: 'Blade',
  Bronya: 'Bronya',
  Clara: 'Clara',
  BrRatio: 'BrRatio',
  FuXuan: 'FuXuan',
  Hook: 'Hook',
  Jingliu: 'Jingliu',
  Kafka: 'Kafka',
  Luka: 'Luka',
  Luocha: 'Luocha',
  March7: 'March7',
  Natasha: 'Natasha',
  Pela: 'Pela',
  Quingque: 'Quingque',
  RuanMei: 'RuanMei',
  Sampo: 'Sampo',
  Serval: 'Serval',
  Sparkle: 'Sparkle',
  Tingyun: 'Tingyun',
  Topaz: 'Topaz',
  Trailblazer: 'Trailblazer',
  Xueyi: 'Xueyi',
  Yukong: 'Yukong',
} as const;
export type Character = (typeof Character)[keyof typeof Character];
