export type RelicType = {
  location: string;
  lvl: number;
  oldLocation: string;
  set: string;
  slot: string;
  stars: number;
  stat: string;
  subStats?: RelicSubStatType;
};
export type RelicSubStatType = Record<string, number | undefined>;

export const RelicSet = {
  BAND_OF_SIZZLING_THUNDER: 'BAND_OF_SIZZLING_THUNDER',
  BELOBOG_OF_THE_ARCHITECTS: 'BELOBOG_OF_THE_ARCHITECTS',
  BROKEN_KEEL: 'BROKEN_KEEL',
  CELESTIAL_DIFFERENTIATOR: 'CELESTIAL_DIFFERENTIATOR',
  CHAMPION_OF_STREETWISE_BOXING: 'CHAMPION_OF_STREETWISE_BOXING',
  EAGLE_OF_TWILIGHT_LINE: 'EAGLE_OF_TWILIGHT_LINE',
  FIRESMITH_OF_LAVA_FORGING: 'FIRESMITH_OF_LAVA_FORGING',
  FLEET_OF_THE_AGELESS: 'FLEET_OF_THE_AGELESS',
  GENIUS_OF_BRILLIANT_STARS: 'GENIUS_OF_BRILLIANT_STARS',
  GUARD_OF_WUTHERING_SNOW: 'GUARD_OF_WUTHERING_SNOW',
  HUNTER_OF_GLACIAL_FOREST: 'HUNTER_OF_GLACIAL_FOREST',
  INERT_SALSOTTO: 'INERT_SALSOTTO',
  KNIGHT_OF_PURITY_PALACE: 'KNIGHT_OF_PURITY_PALACE',
  LONGEVOUS_DISCIPLE: 'LONGEVOUS_DISCIPLE',
  MESSENGER_TRAVERSING_HACKERSPACE: 'MESSENGER_TRAVERSING_HACKERSPACE',
  MUSKETEER_OF_WILD_WHEAT: 'MUSKETEER_OF_WILD_WHEAT',
  PAN_GALACTIC_COMMERCIAL_ENTERPRISE: 'PAN_GALACTIC_COMMERCIAL_ENTERPRISE',
  PASSERBY_OF_WANDERING_CLOUD: 'PASSERBY_OF_WANDERING_CLOUD',
  PRISONER_IN_DEEP_CONFINEMENT: 'PRISONER_IN_DEEP_CONFINEMENT',
  RUTILANT_ARENA: 'RUTILANT_ARENA',
  SPACE_SEALING_STATION: 'SPACE_SEALING_STATION',
  SPRIGHTLY_VONWACQ: 'SPRIGHTLY_VONWACQ',
  TALIA_KINGDOM_OF_BANDITRY: 'TALIA_KINGDOM_OF_BANDITRY',
  THE_ASHBLAZING_GRAND_DUKE: 'THE_ASHBLAZING_GRAND_DUKE',
  THIEF_OF_SHOOTING_METEOR: 'THIEF_OF_SHOOTING_METEOR',
  WASTELANDER_OF_BANDITRY_DESERT: 'WASTELANDER_OF_BANDITRY_DESERT',
} as const;
export type RelicSet = (typeof RelicSet)[keyof typeof RelicSet];

export const RelicSlot = {
  BODY: 'BODY',
  FEET: 'FEET',
  HAND: 'HAND',
  HEAD: 'HEAD',
  LINK_ROPE: 'LINK_ROPE',
  PLANAR_SPHERE: 'PLANAR_SPHERE',
} as const;
export type RelicSlot = (typeof RelicSlot)[keyof typeof RelicSlot];
